apiVersion: v1
kind: Service
metadata:
  name: elasticsearch7
  namespace: es1
spec:
  selector:
    app: elasticsearch7
  type: NodePort
  ports:
    - port: 9200
      nodePort: 30001
      targetPort: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es7-cluster
  namespace: es1
spec:
  serviceName: elasticsearch7
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch7
  template:
    metadata:
      labels:
        app: elasticsearch7
    spec:
      containers:
        - name: elasticsearch7
          image: elasticsearch:7.16.2
          resources:
            requests:
              memory: 2048Mi
              cpu: 1024m
            limits:
              memory: 10240Mi
              cpu: 4096m
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: cluster.name
              value: k8s-logs
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.zen.minimum_master_nodes
              value: "2"
            - name: discovery.seed_hosts
              value: "es7-cluster-0.elasticsearch7,es7-cluster-1.elasticsearch7,es7-cluster-2.elasticsearch7"
            - name: cluster.initial_master_nodes
              value: "es7-cluster-0,es7-cluster-1,es7-cluster-2"
            - name: ES_JAVA_OPTS
              value: "-Xms8g -Xmx8g"
      tolerations:
        - key: "node/roles"
          operator: "Equal"
          value: "operat"
          effect: "NoSchedule"
      initContainers:
        - name: fix-permissions
          image: 172.23.101.176/ops/busybox:latest
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: 172.23.101.176/ops/busybox:latest
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: 172.23.101.176/ops/busybox:latest
          command: ["sh", "-c", "ulimit -n 65536"]

  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        storageClassName: alicloud-disk-essd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
