apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  namespace: observability
  labels:
    app: elasticsearch
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

