apiVersion: v1
kind: Service
metadata:
  name: jaeger-svc
  namespace: observability
spec:
  ports:
    - name: http-query
      port: 16686
      protocol: TCP
      targetPort: 16686
      nodePort: 31111
  selector:
    app: jaeger
  sessionAffinity: None
  type: NodePort
