kind: Secret
apiVersion: v1
metadata:
  name: rmq-cluster-secret
  namespace: rabbitmq
stringData:
  cookie: ERLANG_COOKIE
  password: 123456admin
  url: amqp://root:123456admin@rmq-cluster-balancer
  username: root
type: Opaque
